name       : radeontop
version    : 1.1
release    : 3
source     :
    - git|https://github.com/clbr/radeontop.git : v1.1
license    : GPL-3.0-or-later
component  : system.utils
summary    : top style utility for Radeon GPUs
description: |
    View your GPU utilization, both for the total activity percent and individual blocks.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(xcb)
install    : |
    %make_install amdgpu=1
