name       : radeontop
version    : 1.0
release    : 2
source     :
    - https://github.com/clbr/radeontop/archive/v1.0.tar.gz : a997ea92f38a53d59db4d8e846aec4cc04cee8b79939e89d5eb9e31c57b468fc
license    : GPL-3.0
component  : system.utils
summary    : top style utility for Radeon GPUs
description: |
    View your GPU utilization, both for the total activity percent and individual blocks.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(xcb)
install    : |
    %make_install amdgpu=1
