name       : radeontop
version    : 1.1
release    : 5
source     :
    - git|https://github.com/clbr/radeontop.git : v1.1
license    : GPL-3.0-or-later
component  : system.utils
summary    : top style utility for Radeon GPUs
description: |
    View your GPU utilization, both for the total activity percent and individual blocks.
libsplit   : no
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(xcb)
install    : |
    %make_install LIBDIR=lib64 amdgpu=1
replaces   :
    - radeontop-devel
