name       : radeontop
version    : 1.3
release    : 8
source     :
    - https://github.com/clbr/radeontop/archive/refs/tags/v1.3.tar.gz : 0e6abacafa3c795ee783be18b736f6dfc7ff93c6e3c3237cc7c1684863e08100
license    : GPL-3.0-or-later
component  : system.utils
summary    : top style utility for Radeon GPUs
description: |
    View your GPU utilization, both for the total activity percent and individual blocks.
replaces   :
    - radeontop-devel
libsplit   : no
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(xcb)
setup      : |
    # Install binary to /usr/bin instead of /usr/sbin
    %patch -p1 < $pkgfiles/0001-install-radeontop-to-usr-bin.patch

    # Fix version (broken because we are using an archive instead of git source)
    sed -e "s/unknown/$version/" -i getver.sh
install    : |
    %make_install LIBDIR=lib64 amdgpu=1
